### ISSUE TITLE
Can I change the default code font in markdown code blocks?

### ISSUE THREAD

**Issue by DingShizhe** [marktext/marktext#187]
### Description

I noticed that default codes font in code blocks is Courier (or Courier New) and I want to change it to Consolas.  I try to change css file in static/themes/ then build, but it doesn't work.

In line 349 of file dark.css, I changed the code as show below. 
``` css
code {
  ...
  font-family: Menlo, Monaco, Consolas, "Courier New", monospace;
}
```

``` css 
code {
  ...
  font-family: Consolas;
}
```

Is there some ways to change the font?

### Versions

- OS: Ubuntu 16.04
