### ISSUE TITLE
Failed to add sandbox / use mas build for marktext

### ISSUE THREAD

**Issue by develorer** [marktext/marktext#3437]
### Description

I tried adding the sandbox entitlement and selecting the build "mas" for electron. But launching the app then fails with the error :

`process_singleton_posix.cc(1184)] Failed to bind() /var/folders/s2/j0z79krx43qgmt8l71r95_zc0000gn/T/com.electron.logseq/S/SingletonSocket: Operation not permitted (1) 
`
- [ X] I can reproduce the issue 

### Steps to reproduce

1. Use a macOS system
2. git clone marktext repo
3. modify `electron-builder.yml` to the following to force a `mas` build :
```
mac:
  artifactName: "marktext-${arch}-mac.${ext}"
  icon: "resources/icons/icon.icns"
  darkModeSupport: true
  target:
    #- target: dmg
    #  arch: [x64, arm64]
    #- target: zip
    #  arch: [x64, arm64]
    - target: mas
      arch: [arm64]
```
4. codesign as appropriate, add `ElectronTeamId` in `Info.plist` of the main bundle
5. launch the app

**Expected behavior:**

The app launches correctly

**Actual behavior:**

App fails with the message `process_singleton_posix.cc(1184)] Failed to bind() /var/folders/s2/j0z79krx43qgmt8l71r95_zc0000gn/T/com.electron.logseq/S/SingletonSocket: Operation not permitted (1) 
`

(indicating it tries to bind a socket outside the app's sandbox container).

**Link to an example: [optional]**

### Versions

- MarkText version: 0.17.1
- Operating system: macOS Monterey 12.5.1
