### ISSUE TITLE
 如何增加章节编号（或者如何使用自定义的 css 样式）

### ISSUE THREAD

**Issue by ShawnZhuang** [marktext/marktext#3471]
如何增加章节编号（或者可否使用自定义的 css 样式）

**Comment by Jocs** [comment]
MarkText 支持通过 **Preferences > Theme** 中的 **`customCss`** 字段自定义 CSS 样式。章节编号可通过 CSS 计数器实现：
```css
body { counter-reset: h1counter h2counter; }
h1::before { counter-increment: h1counter; content: counter(h1counter) '. '; }
h2::before { counter-increment: h2counter; content: counter(h1counter) '.' counter(h2counter) ' '; }
```
关闭此 issue，问题已有解答。
